
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
#spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
#spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
#spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.datasource.url=jdbc:mysql://primary.mysql-db--nh6z6xg7dlfx.addon.code.run:3306/09be25c5857b
spring.datasource.username=e1bd45e1797c85ad
spring.datasource.password=278b74d6d49d15d6bb589de2822dce
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
