
# conexion a mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/recursos_humanos_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=*!OH,godzila_Q45
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#  conexión JDBC
spring.datasource.url=jdbc:mysql://primary.basemysql-datos--yblb892jy5ym.addon.code.run:3306/39300a158015

# Usuario y contraseña
spring.datasource.username=35ae8f21fdb1f51c
spring.datasource.password=f32fdc84afeaccc2abe05c61760a7e

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Opcional: configuración de Hibernate (si usas JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
